runtime: python39  # even though you aren't using Python, this is good for serving static files

handlers:
- url: /
  static_files: index.html
  upload: index.html
- url: /(.*)
  static_files: \1
  upload: (.*)
